[2022-06-29 21:17:12,601] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: SDG_Enrique_V0.postgreSQL_getTable 2022-06-29T21:17:09.558978+00:00 [queued]>
[2022-06-29 21:17:12,629] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: SDG_Enrique_V0.postgreSQL_getTable 2022-06-29T21:17:09.558978+00:00 [queued]>
[2022-06-29 21:17:12,630] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-29 21:17:12,632] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-06-29 21:17:12,633] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-29 21:17:12,650] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): postgreSQL_getTable> on 2022-06-29T21:17:09.558978+00:00
[2022-06-29 21:17:12,659] {standard_task_runner.py:52} INFO - Started process 227 to run task
[2022-06-29 21:17:12,669] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'SDG_Enrique_V0', 'postgreSQL_getTable', '2022-06-29T21:17:09.558978+00:00', '--job-id', '1440', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/company_forecasting.py', '--cfg-path', '/tmp/tmpze700m_3', '--error-file', '/tmp/tmp73benp5l']
[2022-06-29 21:17:12,673] {standard_task_runner.py:77} INFO - Job 1440: Subtask postgreSQL_getTable
[2022-06-29 21:17:12,791] {logging_mixin.py:104} INFO - Running <TaskInstance: SDG_Enrique_V0.postgreSQL_getTable 2022-06-29T21:17:09.558978+00:00 [running]> on host 3cf820b1df4c
[2022-06-29 21:17:12,893] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=enrique-liebana@outlook.com
AIRFLOW_CTX_DAG_OWNER=Enrique Liebana Pe√±a
AIRFLOW_CTX_DAG_ID=SDG_Enrique_V0
AIRFLOW_CTX_TASK_ID=postgreSQL_getTable
AIRFLOW_CTX_EXECUTION_DATE=2022-06-29T21:17:09.558978+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-29T21:17:09.558978+00:00
[2022-06-29 21:17:12,909] {base.py:74} INFO - Using connection to: id: postgres_conection. Host: host.docker.internal, Port: 5432, Schema: data_company, Login: airflow, Password: XXXXXXXX, extra: None
[2022-06-29 21:17:40,292] {company_forecasting.py:55} INFO - Backup Company data in : /raw_data/company.csv
[2022-06-29 21:17:40,296] {python.py:118} INFO - Done. Returned value was: None
[2022-06-29 21:17:40,314] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=SDG_Enrique_V0, task_id=postgreSQL_getTable, execution_date=20220629T211709, start_date=20220629T211712, end_date=20220629T211740
[2022-06-29 21:17:40,384] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-29 21:17:40,460] {local_task_job.py:146} INFO - Task exited with return code 0
