[2022-06-29 21:42:03,838] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: SDG_Enrique_V0.postgreSQL_getTable 2022-06-29T21:42:01.323542+00:00 [queued]>
[2022-06-29 21:42:04,017] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: SDG_Enrique_V0.postgreSQL_getTable 2022-06-29T21:42:01.323542+00:00 [queued]>
[2022-06-29 21:42:04,020] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-29 21:42:04,023] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-06-29 21:42:04,026] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-29 21:42:04,069] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): postgreSQL_getTable> on 2022-06-29T21:42:01.323542+00:00
[2022-06-29 21:42:04,588] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'SDG_Enrique_V0', 'postgreSQL_getTable', '2022-06-29T21:42:01.323542+00:00', '--job-id', '1451', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/company_forecasting.py', '--cfg-path', '/tmp/tmp9cy3eebj', '--error-file', '/tmp/tmpdi57l5jc']
[2022-06-29 21:42:04,620] {standard_task_runner.py:77} INFO - Job 1451: Subtask postgreSQL_getTable
[2022-06-29 21:42:04,543] {standard_task_runner.py:52} INFO - Started process 2350 to run task
[2022-06-29 21:42:05,604] {logging_mixin.py:104} INFO - Running <TaskInstance: SDG_Enrique_V0.postgreSQL_getTable 2022-06-29T21:42:01.323542+00:00 [running]> on host 3cf820b1df4c
[2022-06-29 21:42:05,715] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=enrique-liebana@outlook.com
AIRFLOW_CTX_DAG_OWNER=Enrique Liebana Pe√±a
AIRFLOW_CTX_DAG_ID=SDG_Enrique_V0
AIRFLOW_CTX_TASK_ID=postgreSQL_getTable
AIRFLOW_CTX_EXECUTION_DATE=2022-06-29T21:42:01.323542+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-29T21:42:01.323542+00:00
[2022-06-29 21:42:05,748] {base.py:74} INFO - Using connection to: id: postgres_conection. Host: host.docker.internal, Port: 5432, Schema: data_company, Login: airflow, Password: XXXXXXXX, extra: None
[2022-06-29 21:42:28,974] {company_forecasting.py:55} INFO - Backup Company data in : /raw_data/company.csv
[2022-06-29 21:42:28,978] {python.py:118} INFO - Done. Returned value was: None
[2022-06-29 21:42:28,991] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=SDG_Enrique_V0, task_id=postgreSQL_getTable, execution_date=20220629T214201, start_date=20220629T214203, end_date=20220629T214228
[2022-06-29 21:42:29,019] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-29 21:42:29,067] {local_task_job.py:146} INFO - Task exited with return code 0
