[2022-06-26 20:17:57,785] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trigger_dag.gridSearchLR 2022-06-26T20:17:55.830974+00:00 [queued]>
[2022-06-26 20:17:57,801] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trigger_dag.gridSearchLR 2022-06-26T20:17:55.830974+00:00 [queued]>
[2022-06-26 20:17:57,802] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-26 20:17:57,803] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-06-26 20:17:57,804] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-26 20:17:57,812] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): gridSearchLR> on 2022-06-26T20:17:55.830974+00:00
[2022-06-26 20:17:57,820] {standard_task_runner.py:52} INFO - Started process 5091 to run task
[2022-06-26 20:17:57,824] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'gridSearchLR', '2022-06-26T20:17:55.830974+00:00', '--job-id', '303', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpaiva0k89', '--error-file', '/tmp/tmpwxqb_4e7']
[2022-06-26 20:17:57,827] {standard_task_runner.py:77} INFO - Job 303: Subtask gridSearchLR
[2022-06-26 20:17:57,871] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_dag.gridSearchLR 2022-06-26T20:17:55.830974+00:00 [running]> on host 6fc8504e86cf
[2022-06-26 20:17:57,910] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_dag
AIRFLOW_CTX_TASK_ID=gridSearchLR
AIRFLOW_CTX_EXECUTION_DATE=2022-06-26T20:17:55.830974+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-26T20:17:55.830974+00:00
[2022-06-26 20:17:57,937] {taskinstance.py:1455} ERROR - Experiment 'mLflow SDG' already exists.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/trigger_dag.py", line 27, in check_mlflow_setting
    experiment_id = mlflow.create_experiment("mLflow SDG")
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 936, in create_experiment
    return MlflowClient().create_experiment(name, artifact_location, tags)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/client.py", line 507, in create_experiment
    return self._tracking_client.create_experiment(name, artifact_location, tags)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 185, in create_experiment
    tags=[ExperimentTag(key, value) for (key, value) in tags.items()] if tags else [],
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 321, in create_experiment
    self._validate_experiment_name(name)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 316, in _validate_experiment_name
    databricks_pb2.RESOURCE_ALREADY_EXISTS,
mlflow.exceptions.MlflowException: Experiment 'mLflow SDG' already exists.
[2022-06-26 20:17:57,942] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=gridSearchLR, execution_date=20220626T201755, start_date=20220626T201757, end_date=20220626T201757
[2022-06-26 20:17:58,002] {local_task_job.py:146} INFO - Task exited with return code 1
